spring:
 application:
  name: spring-ai-poc
 ai:
  ollama:
   base-url: http://localhost:11434
   chat:
     options:
      model: llama3
 data:
  mongodb:
   uri: mongodb://localhost:27017/ollama-chatbot

